### ISSUE TITLE
Get Method not found for 'Name'

### ISSUE THREAD

**Issue by NickAcPT** [protobuf-net/protobuf-net.Grpc#90]
Hi, I'm working on Blazor WebAssembly application and I've come across this problem:
```
The type initializer for 'DefaultProxyCache`3' threw an exception.
System.TypeInitializationException: The type initializer for 'DefaultProxyCache`3' threw an exception. ---> System.ArgumentException: Get Method not found for 'Name'
  at System.Reflection.RuntimePropertyInfo.GetValue (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] index, System.Globalization.CultureInfo culture) <0x2583f68 + 0x00048> in <filename unknown>:0 
  at System.Reflection.RuntimePropertyInfo.GetValue (System.Object obj, System.Object[] index) <0x2583e80 + 0x00024> in <filename unknown>:0 
  at System.Reflection.PropertyInfo.GetValue (System.Object obj) <0x2583d30 + 0x0000c> in <filename unknown>:0 
  at ProtoBuf.Grpc.Configuration.ServiceBinder.TryGetProperty[T] (System.Attribute obj, System.String name, T& value) <0x2583bc0 + 0x00046> in <filename unknown>:0 
  at ProtoBuf.Grpc.Configuration.ServiceBinder.IsServiceContract (System.Type contractType, System.String& name) <0x25776b8 + 0x000ac> in <filename unknown>:0 
  at ProtoBuf.Grpc.Internal.ProxyEmitter.CreateFactory[TChannel,TService] (System.Type baseType, ProtoBuf.Grpc.Configuration.BinderConfiguration binderConfig) <0x256ef78 + 0x002c8> in <filename unknown>:0 
  at ProtoBuf.Grpc.Configuration.ClientFactory+DefaultProxyCache`3[TBase,TService,TChannel]..cctor () <0x24eff18 + 0x0000a> in <filename unknown>:0 
   --- End of inner exception stack trace ---
  at ProtoBuf.Grpc.Configuration.ClientFactory+DefaultClientFactory.CreateClient[TBase,TService,TChannel] (TChannel channel) <0x24efb60 + 0x00000> in <filename unknown>:0 
  at ProtoBuf.Grpc.Configuration.ClientFactory.CreateClient[TService] (Grpc.Core.CallInvoker channel) <0x24ef930 + 0x0000a> in <filename unknown>:0 
  at ProtoBuf.Grpc.Client.GrpcClientFactory.CreateGrpcService[TService] (Grpc.Core.ChannelBase client, ProtoBuf.Grpc.Configuration.ClientFactory clientFactory) <0x24ef088 + 0x00024> in <filename unknown>:0 
```

And I think the problem is somehow in https://github.com/protobuf-net/protobuf-net.Grpc/blob/master/src/protobuf-net.Grpc/Configuration/ServiceBinder.cs#L152-L169.

It appears to me that there is needed a try-catch there just to be sure nothing blows up and it fails gracefully.

This only happens when my application is on Release mode where optimizations are enabled.

**Comment by mgravell** [comment]
Pruning and reflection don't play nicely.

I have a plan to implement build-time AOT client implementations via the new prototype "generators" feature, but that isn't ready to ship yet.

For now, you could:

- disable pruning for the affected type (I can help you figure out which this is, if you have a repro GitHub I can play with, but my guess is the **attributes**), or
- use the untyped client

**Comment by NickAcPT** [comment]
> * disable pruning for the affected type (I can help you figure out which this is, if you have a repro GitHub I can play with, but my guess is the **attributes**), or

I've looked into doing this, but haven't found out exactly how to do it.

**Comment by NickAcPT** [comment]
Okay so, I've tried messing with the LinterConfig, but failed to fix the error on Release (it's not present on the Debug configuration).

Since I wasn't able to find a way to fix it, I've decided to create a sample project where the problem can be replicated. The code is over at https://github.com/NickAcPT/BlazorApp5

It's the default webassembly app, but I changed the Fetch Data tab to connect to a Grpc server. There is no need to have an actual server to be able to replicate this bug.

When running on the Debug configuration, one should be able to see this after opening the fetch data page.
![Image](https://i.imgur.com/7Wss7eU.png)

**Comment by mgravell** [comment]
Yup, definitely tree shaking. It has removed the getter on the attribute (but left the fact that an attribute was there). There is a second attribute metadata API I can try using - `CustomAttributeData` - the advantage being that it doesn't rely on materialization, so might not hit this problem. I will give this a go.

There may be ways to educate the linker not to remove the getters - I will try to find out that too, but I'm not a blazor expert.

Long term, the "real real" fix here is "generators", removing all the runtime reflection etc.

**Comment by NickAcPT** [comment]
Hope I'm not being annoying, but is there anything that can be done while the solution you mentioned isn't implemented?

**Comment by mgravell** [comment]
Huh, I could have sworn someone else posted back with the linker config example. Might have been a different post - one moment, I'll look.

**Comment by mgravell** [comment]
I think this does it: https://github.com/NickAcPT/BlazorApp5/pull/1

Please check and let me know

**Comment by mgravell** [comment]
And here's the work to try and make it work *without* that; I'll see if I can get that working in your blazor example before I merge it: https://github.com/protobuf-net/protobuf-net.Grpc/pull/93

**Comment by mgravell** [comment]
Dammit,  I screwed up that PR; recreated as #94 - ignore #93

**Comment by NickAcPT** [comment]
Okay so, I've tested that your linker workaround has worked for me on both the example project and my project.
Later I'll try to test #94 without the linker configuration and report back.

**Comment by mgravell** [comment]
Fixed next deploy

**Comment by maxgsamson** [comment]
+1 got the same problem as of 2.47.0...

It happens only when static WASM files are not served by Visual Studio as debug run.
Once published... TypeInitialization_Type, DefaultProxyCache`1 pops out.

Linker Config workaround is not working!

Any ideas?

**Comment by lombardk** [comment]
Also got same problem after upgrading to 2.47.0. Downgraded to 2.46.0 and problem does not occur.

**Comment by maxgsamson** [comment]
> Also got same problem after upgrading to 2.47.0. Downgraded to 2.46.0 and problem does not occur.

I have tried with those (Server/Client)
Grpc.Net.Client.Web - 2.46.0
Grpc.AspNetCore.Web - 2.46.0
protobuf-net" Version - 3.1.17
protobuf-net.Core - 3.1.17
protobuf-net.Grpc - 1.0.152
protobuf-net.Grpc.AspNetCore - 1.0.152

Still the same problem it works inside visual studio not in published project (Debug/Staging/Production).

To "kinda not" fix our problem, we have decided to add support for RESTful API in our server... and whenever creation of the GRPC channel fails, the client call RESTful instead... it's a working solution.... and if the problem is not fix in a near future we will completely remove GRPC Web all together.

We have been lucky to have built our server in a way to accept RESTful from the start... otherwise it would have cost a lot to make the transition.... It's a nasty problem that goes undetected until rolling out staging tests.

**Comment by mgravell** [comment]
Ok. Is there a minimal way for me to repro this? Assume I'm not hugely a
WASM expert... Happy to try to help, but I need breadcrumbs.

**Comment by wivanw** [comment]
How to Set Up a link.xml File in Unity for protobuf-net on Android:

	1.	Creating the link.xml File:
In Unity, you need to create a link.xml file to ensure the IL2CPP build process does not strip away important metadata from the protobuf-net libraries used for serialization/deserialization. This is crucial for keeping reflection and dynamically determined types working.
	2.	Location of the link.xml File:
The link.xml file should be placed inside any folder within the Assets directory in your Unity project. For example, you can place it in the root Assets folder or a subfolder like Assets/Resources.
	3.	Content of the link.xml File:
Copy the following content into your link.xml file:

```
<linker>
    <!-- Preserve all types and methods from protobuf-net.Core assembly -->
    <assembly fullname="protobuf-net.Core" preserve="all"/>
    <!-- Preserve all types and methods from protobuf-net assembly -->
    <assembly fullname="protobuf-net" preserve="all"/>
</linker>
```

This file tells the Unity linker to preserve all types and methods in the protobuf-net.Core and protobuf-net assemblies, which may be necessary for reflection and serialization.

	4.	Building with IL2CPP:
After creating the link.xml file, build your project with IL2CPP for Android. Unity will take this file into account and prevent stripping of important types and methods from the protobuf-net libraries.
	5.	Verification:
After building, run your app on an Android device and check if the reflection error related to protobuf-net is resolved.

Notes:

	•	If the problem persists, ensure that Unity is processing the link.xml file correctly. You can check the Editor Log to confirm that the linker has applied the file’s instructions.
	•	The link.xml file can be placed anywhere inside the Assets folder as long as Unity recognizes it.
